### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile

### ISSUE THREAD

**Issue by Arwiim** [aws-solutions/scalable-analytics-using-apache-druid-on-aws#37]
![Captura de pantalla 2024-11-07 a la(s) 5 40 44 p  m](https://github.com/user-attachments/assets/73e330d6-1f50-4950-92de-d6e054c78dda)

**Comment by Arwiim** [comment]
This is when i run, npm run build

**Comment by chn217** [comment]
Hi @Arwiim 

CC: @bios6 

Thank you for reporting the issue. The team will look into it and get back to you shortly.

In the meantime, you can use the following workaround in your local workspace:

git diff
diff --git a/source/DruidCloudwatchExtension/pom.xml b/source/DruidCloudwatchExtension/pom.xml
index 65fe85a..634c307 100644
--- a/source/DruidCloudwatchExtension/pom.xml
+++ b/source/DruidCloudwatchExtension/pom.xml
@@ -10,8 +10,8 @@
 
     <properties>
         <druid.version>25.0.0</druid.version>
-        <maven.compiler.source>17</maven.compiler.source>
-        <maven.compiler.target>17</maven.compiler.target>
+        <maven.compiler.source>8</maven.compiler.source>
+        <maven.compiler.target>8</maven.compiler.target>
         <jdk.version>17</jdk.version>
     </properties>
 
This should help you pass the build.

Cheers
Frank

**Comment by Arwiim** [comment]
Same error :c, im using macos  sequoia m1 
<img width="1166" alt="Captura de pantalla 2024-11-07 a la(s) 11 47 38 p  m" src="https://github.com/user-attachments/assets/59406ce8-6570-4e92-8804-ecc0f8d0b4ed">

**Comment by Arwiim** [comment]
diff --git a/source/DruidCloudwatchExtension/pom.xml b/source/DruidCloudwatchExtension/pom.xml
index 65fe85a..634c307 100644
--- a/source/DruidCloudwatchExtension/pom.xml
+++ b/source/DruidCloudwatchExtension/pom.xml
@@ -10,8 +10,8 @@
 
     <properties>
         <druid.version>25.0.0</druid.version>
-        <maven.compiler.source>17</maven.compiler.source>
-        <maven.compiler.target>17</maven.compiler.target>
+        <maven.compiler.source>8</maven.compiler.source>
+        <maven.compiler.target>8</maven.compiler.target>
         <jdk.version>17</jdk.version>
     </properties>

**Comment by Arwiim** [comment]
`diff --git a/source/DruidCloudwatchExtension/pom.xml b/source/DruidCloudwatchExtension/pom.xml
index 65fe85a..634c307 100644
--- a/source/DruidCloudwatchExtension/pom.xml
+++ b/source/DruidCloudwatchExtension/pom.xml
@@ -10,8 +10,8 @@
 
     <properties>
         <druid.version>25.0.0</druid.version>
-        <maven.compiler.source>17</maven.compiler.source>
-        <maven.compiler.target>17</maven.compiler.target>
+        <maven.compiler.source>8</maven.compiler.source>
+        <maven.compiler.target>8</maven.compiler.target>
         <jdk.version>17</jdk.version>
     </properties>`

**Comment by Arwiim** [comment]
```
diff --git a/source/DruidCloudwatchExtension/pom.xml b/source/DruidCloudwatchExtension/pom.xml
index 65fe85a..634c307 100644
--- a/source/DruidCloudwatchExtension/pom.xml
+++ b/source/DruidCloudwatchExtension/pom.xml
@@ -10,8 +10,8 @@
 
     <properties>
         <druid.version>25.0.0</druid.version>
-        <maven.compiler.source>17</maven.compiler.source>
-        <maven.compiler.target>17</maven.compiler.target>
+        <maven.compiler.source>8</maven.compiler.source>
+        <maven.compiler.target>8</maven.compiler.target>
         <jdk.version>17</jdk.version>
     </properties>
```

**Comment by chn217** [comment]
Hi @Arwiim 

Which JDK version are you using? Could you paste the output of the `mvn -v` command?

I've been able to reproduce the issue with JDK 23, but please note that this version isn't supported. Druid is compatible with Java 11 and 17, with 17 being the preferred option.

To use Java 17, set the JAVA_HOME environment variable (e.g. export JAVA_HOME="/opt/homebrew/opt/openjdk@17") so that Maven selects the correct Java version. Then, delete the target directory under source/DruidCloudwatchExtension and rebuild the project.

Cheers
Frank

**Comment by Arwiim** [comment]
Also Maven is using jdk17
```
 mvn -v                                                                                       <248 KiB/s >39.3 KiB/s 192.168.100.126 ip 

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec
Java version: 17.0.13, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk@17/17.0.13/libexec/openjdk.jdk/Contents/Home
Default locale: es_419, platform encoding: UTF-8
OS name: "mac os x", version: "15.1", arch: "aarch64", family: "mac"
```

**Comment by aijunpeng** [comment]
We recommend using Java Correto 17. Could you try that? 

```
> java --version
> openjdk 17.0.13 2024-10-15 LTS
> OpenJDK Runtime Environment Corretto-17.0.13.11.1 (build 17.0.13+11-LTS)
> OpenJDK 64-Bit Server VM Corretto-17.0.13.11.1 (build 17.0.13+11-LTS, mixed mode, sharing)
```
If that does not work, please provide more information as follows:
1. What version of the solution you are trying to deploy? 
2. Has the build ever worked for you on this macos sequoia m1 before? If so, have you upgraded your OS recently? Please provide the detail of your OS.
3. Please provide a complete log of your console including all the commands you ran and the output.

**Comment by Arwiim** [comment]
Sme error with Corretto
```
java --version                                                                         <9.71 KiB/s >5.37 KiB/s 192.168.100.126 ip 
openjdk 17.0.13 2024-10-15 LTS
OpenJDK Runtime Environment Corretto-17.0.13.11.1 (build 17.0.13+11-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.13.11.1 (build 17.0.13+11-LTS, mixed mode, sharing)
```

This is the solution, im taking the template of the quickstart 
```
{
    "app": "npx ts-node --prefer-ts-exts bin/druid-infra.ts",
    "watch": {
        "include": ["**"],
        "exclude": [
            "README.md",
            "cdk*.json",
            "**/*.d.ts",
            "**/*.js",
            "tsconfig.json",
            "package*.json",
            "yarn.lock",
            "node_modules",
            "test"
        ]
    },
    "context": {
        "@aws-cdk/aws-apigateway:usagePlanKeyOrderInsensitiveId": true,
        "@aws-cdk/core:stackRelativeExports": true,
        "@aws-cdk/aws-rds:lowercaseDbIdentifier": true,
        "@aws-cdk/aws-lambda:recognizeVersionProps": true,
        "@aws-cdk/aws-lambda:recognizeLayerVersion": true,
        "@aws-cdk/aws-cloudfront:defaultSecurityPolicyTLSv1.2_2021": true,
        "@aws-cdk-containers/ecs-service-extensions:enableDefaultLogDriver": true,
        "@aws-cdk/aws-ec2:uniqueImdsv2TemplateName": true,
        "@aws-cdk/core:checkSecretUsage": true,
        "@aws-cdk/aws-iam:minimizePolicies": true,
        "@aws-cdk/aws-ecs:arnFormatIncludesClusterName": true,
        "@aws-cdk/core:validateSnapshotRemovalPolicy": true,
        "@aws-cdk/aws-codepipeline:crossAccountKeyAliasStackSafeResourceName": true,
        "@aws-cdk/aws-s3:createDefaultLoggingPolicy": true,
        "@aws-cdk/aws-sns-subscriptions:restrictSqsDescryption": true,
        "@aws-cdk/aws-apigateway:disableCloudWatchRole": true,
        "@aws-cdk/core:enablePartitionLiterals": true,
        "@aws-cdk/aws-s3:serverAccessLogsUseBucketPolicy": true,
        "@aws-cdk/core:target-partitions": ["aws", "aws-cn"],

        "retainData": false,
        "vpcCidr": "10.243.224.0/20",
        "druidVersion": "30.0.0",
        "druidOperationPlatform": "eks",
        "druidClusterName": "dev",
        "internetFacing": true,
        "druidExtensions": [
            "druid-hdfs-storage",
            "druid-kafka-indexing-service",
            "druid-datasketches",
            "druid-kinesis-indexing-service",
            "druid-avro-extensions",
            "druid-parquet-extensions",
            "druid-protobuf-extensions",
            "druid-orc-extensions"
        ],
        "druidEksConfig": {
            "endpointAccess": "PUBLIC",
            "clusterMasterPrincipalArn": "arn:aws:iam::211255090713:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS",
            "capacityProviderType": "fargate",
            "capacityProviderConfig": {
                "historical": {
                    "minNodes": 3,
                    "maxNodes": 3,
                    "cpu": 4,
                    "memory": "16Gi"
                },
                "middleManager": {
                    "minNodes": 3,
                    "maxNodes": 3,
                    "cpu": 4,
                    "memory": "16Gi"
                },
                "broker": {
                    "minNodes": 3,
                    "maxNodes": 3,
                    "cpu": 2,
                    "memory": "8Gi"
                },
                "router": {
                    "minNodes": 3,
                    "maxNodes": 3,
                    "cpu": 2,
                    "memory": "8Gi"
                },
                "coordinator": {
                    "minNodes": 1,
                    "maxNodes": 1,
                    "cpu": 2,
                    "memory": "8Gi"
                },
                "overlord": {
                    "minNodes": 1,
                    "maxNodes": 1,
                    "cpu": 2,
                    "memory": "8Gi"
                },
                "zookeeper": {
                    "minNodes": 3,
                    "maxNodes": 3,
                    "cpu": 2,
                    "memory": "4Gi"
                }
            }
        },
        "druidMetadataStoreConfig": {
            "metadataStoreType": "aurora",
            "metadataStoreConfig": {
                "rdsInstanceType": "t3.medium",
                "rdsInstanceCount": 3
            }
        }
    }
}

```

This is the first time building the proyect Mac M1 Sequoia 15.1

The steps was in the src proyect

npm install

npm run build

**Comment by aijunpeng** [comment]
Thanks for the info. Unfortunately I am not able to create a macos sequoia m1 instance therefore I won't be able to replicate that particular issue. A workaround is to build the solution on Amazon Linux 2.

**Comment by chn217** [comment]
Hi @Arwiim 

It looks like a JDK compiler issue to me. Here’s another fix you can try. This solution worked for me to resolve the same issue with JDK 23.

`
caof@603e5f40ecc2:~/workspace/scalable-analytics-using-apache-druid-on-aws4/source/DruidCloudwatchExtension$ git diff
diff --git a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
index 639a89a..c798c12 100644
--- a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
+++ b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
@@ -71,7 +71,7 @@ public class CloudwatchEmitter implements Emitter {
     private final ObjectMapper jsonMapper;
 
     // set to nosonar because it causes a false positive
-    private final CloudwatchEmitterConfig config; // NOSONAR
+    private CloudwatchEmitterConfig config; // NOSONAR
 
     private final DruidMonitoringMetricsFactory druidMonitoringMetricsFactory;
 
diff --git a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
index c188a6b..4f3e2a5 100644
--- a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
+++ b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
@@ -67,7 +67,7 @@ public class DruidMonitoringMetricsFactory {
 
     private final List<String> dimensionBlacklist;
 
-    private final CloudwatchEmitterConfig config;
+    private CloudwatchEmitterConfig config;
 
     public DruidMonitoringMetricsFactory(CloudwatchEmitterConfig config) {
         this.config = config;
`
Cheers

**Comment by aijunpeng** [comment]
Hi Frank,

Do you see this comment of yours in GitHub? We (Abhay and me) don’t see it in GitHub. This is strange. Could you repost it if you want the comment to be seen by public?

Thank you!

Regards,
Aijun
From: Frank Cao ***@***.***>
Reply-To: aws-solutions/scalable-analytics-using-apache-druid-on-aws ***@***.***>
Date: Monday, November 11, 2024 at 3:42 PM
To: aws-solutions/scalable-analytics-using-apache-druid-on-aws ***@***.***>
Cc: "Peng, Aijun" ***@***.***>, Comment ***@***.***>
Subject: Re: [aws-solutions/scalable-analytics-using-apache-druid-on-aws] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (Issue #37)


Hi @Arwiim<https://github.com/Arwiim>

It looks like a JDK compiler issue to me. Here’s another fix you can try. This solution worked for me to resolve the same issue with JDK 23.

`
***@***.***:~/workspace/scalable-analytics-using-apache-druid-on-aws4/source/DruidCloudwatchExtension$ git diff
diff --git a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
index 639a89a..c798c12 100644
--- a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
+++ b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
@@ -71,7 +71,7 @@ public class CloudwatchEmitter implements Emitter {
private final ObjectMapper jsonMapper;

 // set to nosonar because it causes a false positive

  *   private final CloudwatchEmitterConfig config; // NOSONAR

  *   private CloudwatchEmitterConfig config; // NOSONAR

private final DruidMonitoringMetricsFactory druidMonitoringMetricsFactory;

diff --git a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
index c188a6b..4f3e2a5 100644
--- a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
+++ b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
@@ -67,7 +67,7 @@ public class DruidMonitoringMetricsFactory {

 private final List<String> dimensionBlacklist;

  *   private final CloudwatchEmitterConfig config;

  *   private CloudwatchEmitterConfig config;

public DruidMonitoringMetricsFactory(CloudwatchEmitterConfig config) {
this.config = config;
`
Cheers

**Comment by aijunpeng** [comment]
Hi Aijun,
I deleted my original comment because I found that this fix only works intermittently. It appears to be a compiler issue, though the root cause is still unclear. I'd like to spend more time understanding the problem to develop a more reliable fix. For now, I agree that suggesting the customer move to an EC2 host for building is a sensible approach.
Cheers,
Frank

From: "Peng, Aijun" ***@***.***>
Date: Wednesday 13 November 2024 at 5:37 AM
To: aws-solutions/scalable-analytics-using-apache-druid-on-aws ***@***.***>, aws-solutions/scalable-analytics-using-apache-druid-on-aws ***@***.***>, "Cao, Frank" ***@***.***>, "Joshi, Abhay" ***@***.***>
Cc: Comment ***@***.***>
Subject: Re: [aws-solutions/scalable-analytics-using-apache-druid-on-aws] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (Issue #37)

Hi Frank,

Do you see this comment of yours in GitHub? We (Abhay and me) don’t see it in GitHub. This is strange. Could you repost it if you want the comment to be seen by public?

Thank you!

Regards,
Aijun
From: Frank Cao ***@***.***>
Reply-To: aws-solutions/scalable-analytics-using-apache-druid-on-aws ***@***.***>
Date: Monday, November 11, 2024 at 3:42 PM
To: aws-solutions/scalable-analytics-using-apache-druid-on-aws ***@***.***>
Cc: "Peng, Aijun" ***@***.***>, Comment ***@***.***>
Subject: Re: [aws-solutions/scalable-analytics-using-apache-druid-on-aws] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (Issue #37)


Hi @Arwiim<https://github.com/Arwiim>

It looks like a JDK compiler issue to me. Here’s another fix you can try. This solution worked for me to resolve the same issue with JDK 23.

`
***@***.***:~/workspace/scalable-analytics-using-apache-druid-on-aws4/source/DruidCloudwatchExtension$ git diff
diff --git a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
index 639a89a..c798c12 100644
--- a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
+++ b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/CloudwatchEmitter.java
@@ -71,7 +71,7 @@ public class CloudwatchEmitter implements Emitter {
private final ObjectMapper jsonMapper;

 // set to nosonar because it causes a false positive

  *   private final CloudwatchEmitterConfig config; // NOSONAR

  *   private CloudwatchEmitterConfig config; // NOSONAR

private final DruidMonitoringMetricsFactory druidMonitoringMetricsFactory;

diff --git a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
index c188a6b..4f3e2a5 100644
--- a/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
+++ b/source/DruidCloudwatchExtension/src/main/java/com/amazon/solutions/druid/cloudwatch/DruidMonitoringMetricsFactory.java
@@ -67,7 +67,7 @@ public class DruidMonitoringMetricsFactory {

 private final List<String> dimensionBlacklist;

  *   private final CloudwatchEmitterConfig config;

  *   private CloudwatchEmitterConfig config;

public DruidMonitoringMetricsFactory(CloudwatchEmitterConfig config) {
this.config = config;
`
Cheers

**Comment by aijunpeng** [comment]
Close the ticket for now. Feel free to reopen the ticket if there is any new information.
